import React from "react";

export { default as AddProductToCartForm } from "./AddProductToCartForm";
export { default as Admin } from "./Admin/Admin";
export { default as Cart } from "./Cart.js";
// export { default as ChangeAdminForm } from "./Admin/ChangeAdminForm.js";
// export { default as CreateCollectionForm } from "./Admin/CreateCollectionForm";
// export { default as CreateProductForm } from "./Admin/CreateProductForm";
export { default as CheckoutPage } from "./CheckoutPage.js";
export { default as Collection } from "./Collection.js";
export { default as Collections } from "./Collections.js";
// export { default as DeleteCollectionForm } from "./Admin/DeleteCollectionForm";
// export { default as DeleteProductForm } from "./Admin/DeleteProductForm";
export { default as DeliveryInfo } from "./DeliveryInfo";
// export { default as EditCollectionForm } from "./Admin/EditCollectionForm";
// export { default as EditOrDeleteCollection } from "./Admin/EditOrDeleteCollection";
// export { default as EditOrDeleteProduct } from "./Admin/EditOrDeleteProduct";
// export { default as EditOrDeleteTemp } from "./Admin/EditOrDeleteTemp";
// export { default as EditProductForm } from "./Admin/EditProductForm";
export { default as Home } from "./Home";
export { default as Loading } from "./Loading";
export { default as Login } from "./Login";
export { default as Nav } from "./Nav";
export { default as Products } from "./Products";
export { default as PaymentInfo } from "./PaymentInfo";
export { default as Register } from "./Register";
export { default as SingleProduct } from "./SingleProduct";
